image: alpine:latest
stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$VPS_KEY" > ~/.ssh/id_ed25519.pem
    - chmod 600 ~/.ssh/id_ed25519.pem
  script:
    - echo "Deploying to VPS"
    - |
      ssh -i ~/.ssh/id_ed25519.pem -o StrictHostKeyChecking=no -t root@$VPS_IP << EOF
      echo "Navigating to project directory"
      cd jarfish || exit 1
      echo "Pulling latest commit"
      git pull origin development || exit 1
      echo "Building docker image"
      docker build -t jarfish:latest . || exit 1
      echo "Stopping and removing previous container"
      docker stop project-jarfish || true
      docker rm project-jarfish || true
      echo "Running the latest image in a new container"
      docker run -d --name project-jarfish jarfish:latest || exit 1
      echo "Pruning dangling images"
      docker image prune -f || exit 1
      EOF
  only:
    - development
